@baseUrl = http://localhost:3000

# Messages
###
# @name MessagesController
GET {{baseUrl}}/messages/
?limit=10
&offset=10
### Retorna recado por ID
GET {{baseUrl}}/messages/2/
### Cria um recado
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "text": "New message",
    "from": "Joana",
    "to": "João",
    "read": false,
    "date": "2025-01-16T16:46:24.472Z"
  }
### Atualiza um recado
PATCH {{baseUrl}}/messages/2/
Content-Type: application/json

{
    "text": "Update message 2",
    "from": "Joana",
    "to": "João",
    "read": false,
    "date": "2025-01-16T16:46:24.472Z"
  }
###Apaga um recado
DELETE {{baseUrl}}/messages/2/