@baseUrl = http://localhost:3000

# Messages
###
# @name MessagesController
GET {{baseUrl}}/messages/
?limit=10
&offset=10
### Retorna recado por ID
GET {{baseUrl}}/messages/4/
### Cria um recado
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "New message",
  "from": "Joana",
  "to": "João"
}
### Atualiza um recado
PATCH {{baseUrl}}/messages/4/
Content-Type: application/json

  {
    "text": "Update message 43",
    "from": "Samuel",
    "to": "faxina"
  }
###Apaga um recado
DELETE {{baseUrl}}/messages/3/